dataset:
  name: tweet_topic
  path: cardiffnlp/super_tweeteval

environment:
  num_gpus: 1

reproduce:
  seed: 42

plm:
  model_name: t5
  model_path: t5-small
  optimize: 
    freeze_para: True

train:
  num_epochs: 5
  batch_size: 2
  teacher_forcing: True
  gradient_accumulation_steps: 2 
  gradient_clipping: 1.0 

task: classification

classification:
  parent_config: task
  metric:  # the first one will be the main one to determine checkpoint.
    - accuracy  # accuracy is the most common metric for single-label classification
    - micro-f1
    - macro-f1
    - precision
    - recall
  loss_function: cross_entropy  ## the loss function for classification (cross-entropy for single-label)

learning_setting: full # selecting from "full", "zero_shot", "few_shot"
few_shot:
  parent_config: learning_setting
  few_shot_sampling: sampling_from_train
  
sampling_from_train:
  parent_config: few_shot_sampling
  num_examples_per_label: 100
  also_sample_dev: True
  num_examples_per_label_dev: 100
  seed:
    - 123

template: soft_template
verbalizer:
  sports: sports
  fitness_&_health: fitness, health
  food_&_dining: food, dining
  family: family
  fashion_&_style: fashion, style
  gaming: gaming
  music: music
  learning_&_educational: learning, education
  science_&_technology: science, technology
  business_&_entrepreneurs: business, entrepreneurs
  film_tv_&_video: film, tv, video
  celebrity_&_pop_culture: celebrity, pop_culture
  arts_&_culture: arts, culture
  diaries_&_daily_life: diaries, daily_life
  other_hobbies: hobbies
  relationships: relationships
  news_&_social_concern: news, social_concern
  youth_&_student_life: youth, students
  travel_&_adventure: travel, adventure

soft_template:
  choice: 0
  file_path: ./template.txt
